"""empty message

Revision ID: 36dae15364c5
Revises: af6765d8ee21
Create Date: 2019-08-16 10:10:05.484105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dae15364c5'
down_revision = 'af6765d8ee21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'medias_pags', ['p_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medias_pags', type_='unique')
    # ### end Alembic commands ###
