"""empty message

Revision ID: 7fb90af2238f
Revises: 36dae15364c5
Create Date: 2019-08-16 10:25:31.103678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb90af2238f'
down_revision = '36dae15364c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias_pag_themes',
    sa.Column('p_t_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.Column('p_t_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('p_t_id')
    )
    op.drop_table('medias_pag__schemes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias_pag__schemes',
    sa.Column('p_t_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('p_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('t_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('p_t_week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('p_t_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('medias_pag_themes')
    # ### end Alembic commands ###
