"""empty message

Revision ID: fed5c5583c50
Revises: 
Create Date: 2019-08-05 09:30:32.259681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed5c5583c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_orders',
    sa.Column('a_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('a_life_time', sa.Integer(), nullable=True),
    sa.Column('a_price', sa.Integer(), nullable=True),
    sa.Column('a_pay_statu', sa.Integer(), nullable=True),
    sa.Column('a_check_scheme_statu', sa.Integer(), nullable=True),
    sa.Column('a_apply_time', sa.Date(), nullable=True),
    sa.Column('a_pay_time', sa.Date(), nullable=True),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('devices',
    sa.Column('d_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('d_code', sa.String(length=128), nullable=True),
    sa.Column('d_name', sa.String(length=32), nullable=True),
    sa.Column('d_sex', sa.Integer(), nullable=True),
    sa.Column('d_address', sa.String(length=32), nullable=True),
    sa.Column('d_type', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Date(), nullable=True),
    sa.Column('d_statu', sa.Integer(), nullable=True),
    sa.Column('d_scheme_size', sa.String(length=32), nullable=True),
    sa.Column('m_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('d_id'),
    sa.UniqueConstraint('d_code')
    )
    op.create_table('schemes',
    sa.Column('s_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.String(length=32), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_account', sa.String(length=32), nullable=True),
    sa.Column('u_name', sa.String(length=32), nullable=True),
    sa.Column('u_phone', sa.String(length=32), nullable=True),
    sa.Column('u_company', sa.String(length=64), nullable=True),
    sa.Column('u_wechat', sa.String(length=32), nullable=True),
    sa.Column('u_qq', sa.String(length=32), nullable=True),
    sa.Column('u_chid', sa.String(length=256), nullable=True),
    sa.Column('u_chkey', sa.String(length=256), nullable=True),
    sa.Column('u_icon', sa.String(length=256), nullable=True),
    sa.Column('u_type', sa.Integer(), nullable=True),
    sa.Column('u_password', sa.String(length=256), nullable=True),
    sa.Column('regist_time', sa.Date(), nullable=True),
    sa.Column('u_statu', sa.Integer(), nullable=True),
    sa.Column('u_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_account'),
    sa.UniqueConstraint('u_phone'),
    sa.UniqueConstraint('u_qq'),
    sa.UniqueConstraint('u_wechat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('schemes')
    op.drop_table('devices')
    op.drop_table('advertising_orders')
    # ### end Alembic commands ###
